### ISSUE TITLE
Css error on initial load with nuxt ssr

### ISSUE THREAD

**Issue by antony989** [naver/egjs-flicking#349]
## Description

When loading nuxt for the first time, css load error occurs.
[https://i.imgur.com/txGIppi.png](url)
`async asyncData(){....}`

Css is displayed normally when data loading is complete.
[https://i.imgur.com/7MmeuRa.png](url)

Maybe this is normal operation.
But I want to fix this.

How do I resolve the following symptoms when loading data into asyncData and in nuxt ssr mode?

client-only? or Should I show it after loading?

**Comment by WoodNeck** [comment]
Hello @antony989!
As Flicking cannot know the element sizes before it's mounted, it's impossible to set CSS based on their sizes.
A common bypass is to set CSS that looks the same whether Flicking is mounted or not.

To support IE9+, you can choose copying CSS values after Flicking is mounted.
But as you can't get elements before it's mounted, you can use CSS `nth-child` property, and disable them after it's mounted.

Or, the easier way is using `display:flex` to the generated elements.
```css
.eg-flick-viewport {
  display: flex;
  display: -ms-flexbox;
}
.eg-flick-camera {
  display: flex;
  display: -ms-flexbox;
  flex-direction: row;
  -ms-flex-direction: row;
}
```
Be careful that it works only on IE10+(with `-ms-` prefix).

I've updated Flicking's Nuxt examples with `diplay:flex` implementation.
See https://codesandbox.io/s/egjsvue-flicking-nuxt-examples-p72nw?file=/assets/common.css (line 237+)
