### ISSUE TITLE
How do I change the options for different widths/heights of the user's screen?

### ISSUE THREAD

**Issue by lna1989** [naver/egjs-flicking#605]
## Description
I can't find an option like "breakpoints" in which it would be possible to override options, for example for devices with a width of <768px : {panelsPerView: 2} and for 768+ devices: {panelsPerView: 4} 

Example from other slider: 

> breakpoints: {
          [tresholds.lg]: {
            perPage: 4,
            pagination: false,
            drag: false,
            type: 'slide',
          },
          [tresholds.md]: {
            perPage: 3,
            pagination: false,
            drag: false,
            type: 'slide',
          },
          [tresholds.sm]: {
            perPage: 2,
            pagination: false,
            drag: false,
            type: 'slide',
          },
          [tresholds.xs]: {
            perPage: 1,
            pagination: false,
            drag: false,
            type: 'slide',
          },
        },

**Comment by WoodNeck** [comment]
Hello @lna1989!
We don't provide such option at the moment, but as Flicking follows your CSS width/height you can try media query.

```css
@media screen and (max-width: 768px) {
  .flicking-camera > * {
    width: 100%;
  }
}

@media screen and (min-width: 1024px) {
  .flicking-camera > * {
    width: 50%;
  }
}

@media screen and (min-width: 1216px) {
  .flicking-camera > * {
    width: 33.3%;
  }
}

@media screen and (min-width: 1408px) {
  .flicking-camera > * {
    width: 25%;
  }
}
```

Set `autoResize` to true and Flicking will update internal sizes automatically.
